DEFAULT_PREFERRED_VELOCITY_FPS = 8
DEFAULT_MAXIMUM_VELOCITY_FPS = 10

DEFAULT_AVAILABLE_WATER_GALLONS = 5000
DEFAULT_REQUIRED_RUNTIME_MINUTES = 60

DEFAULT_MINIMUM_PRESSURE_MARGIN_PSI = 20

DEFAULT_MAX_SIMULTANEOUS_PORTS = 1

DEFAULT_MAX_BUDGET = 4000

DEFAULT_OPTIMIZER_GENERATIONS = 12
DEFAULT_OPTIMIZER_POPULATION_SIZE = 12
